version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqlAPI2
      MYSQL_USER: saggarwal98
      MYSQL_PASSWORD: shubham
    container_name: new_golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./Go
    volumes:
      - "./Go:/go"
    container_name: new_golang_app
    deploy:
      replicas: 5
    ports:
      - "4000:4000"
    tty: true
    depends_on:
      - db
